"""Initial schema baseline

Revision ID: 54eed185bd51
Revises: 68f612722729
Create Date: 2026-07-26 15:26:35.774391

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "54eed185bd51"
down_revision: Union[str, Sequence[str], None] = "68f612722729"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_query_logs_timestamp"), table_name="query_logs")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_query_logs_timestamp"), "query_logs", ["timestamp"], unique=False)
    # ### end Alembic commands ###
