"""Shared keyword definitions for query complexity classification and feature extraction."""

COMPLEX_KEYWORDS = {
    "analyze",
    "compare",
    "evaluate",
    "optimize",
    "architecture",
    "synthesize",
    "argue",
    "critique",
    "prove",
    "derive",
    "logic",
    "math",
    "solve",
    "algorithm",
    "debug",
    "refactor",
    "design",
    "implement",
    "integrate",
    "troubleshoot",
    "performance",
    "complexity",
    "database",
    "infrastructure",
    "scalability",
    "framework",
    "theorem",
    "equation",
    "statistics",
    "hypothesis",
    "kubernetes",
    "docker",
    "microservices",
    "concurrency",
    "asynchronous",
    "ci/cd",
    "pipeline",
    "kafka",
    "distributed",
    "security",
    "authentication",
    "authorization",
}

MEDIUM_KEYWORDS = {
    "how",
    "why",
    "explain",
    "difference",
    "summarize",
    "translate",
    "describe",
    "steps",
    "list",
    "guide",
    "tutorial",
    "overview",
    "examples",
    "meaning",
    "define",
    "concept",
    "history",
    "process",
    "method",
    "generate",
    "write a",
    "draft",
    "deploy",
    "configuration",
    "setup",
    "frontend",
    "backend",
    "schema",
    "rest",
    "graphql",
}

TECHNICAL_TERMS = {
    "algorithm",
    "database",
    "api",
    "server",
    "client",
    "cache",
    "optimization",
    "deployment",
    "architecture",
    "framework",
    "library",
    "dependency",
    "repository",
    "integration",
}

REASONING_KEYWORDS = {
    "why",
    "how",
    "explain",
    "analyze",
    "compare",
    "evaluate",
    "reasoning",
    "logic",
    "proof",
    "demonstrate",
    "justify",
}

ANALYSIS_KEYWORDS = {
    "analyze",
    "analysis",
    "evaluate",
    "assess",
    "review",
    "examine",
    "investigate",
    "synthesize",
    "critique",
}
